.changeset/light-eagles-rule.md
README.md
package.json
src/lib/constants/defaultControlOptions.ts
src/lib/helpers/getTerraDrawModes.ts
src/lib/interfaces/TerradrawMode.ts
tsconfig.lib.json
vite.lib.config.ts

added tsconfig for building library type file

fix: added index.d.ts and fixed package.json

---

.changeset/wise-ads-vanish.md
CONTRIBUTING.md
README.md
package.json
pnpm-lock.yaml
src/routes/+page.svelte
static/index_cdn.html
vite.config.ts

fixes #10
also updated demo website to show selected geojson feature on map

fix: moved maplibre-gl and terra-draw to peerDependencies.

---

.changeset/good-beds-beg.md
src/scss/maplibre-gl-terradraw.scss

fix: fixed bug of angled-rectangle icon in active state. Rotate 45 degree of SVG itself.

---

.changeset/serious-eggs-appear.md
src/lib/MaplibreTerradrawControl.ts
src/lib/constants/defaultControlOptions.ts
src/routes/+page.svelte
src/routes/demo/+page.svelte
src/scss/maplibre-gl-terradraw.scss
static/assets/maplibre-npm-example.txt
static/index_cdn.html

feat: add 'render' mode in default control options in constructor.

---

.changeset/rare-planets-tell.md
src/lib/constants/AvailableModes.ts
src/lib/constants/defaultControlOptions.ts
src/lib/constants/getDefaultModeOptions.ts
src/lib/interfaces/TerradrawModeClass.ts
src/routes/+layout.svelte
src/routes/demo/+page.svelte
src/scss/maplibre-gl-terradraw.scss
static/assets/maplibre-npm-example.txt
static/index_cdn.html
vite.config.ts

feat: added Sensor mode and Sector mode to the plugin.

---

.changeset/kind-radios-fix.md
src/lib/MaplibreTerradrawControl.ts

call TerraDraw.stop() when calling onRemove()

---

.changeset/friendly-vans-hammer.md
src/lib/MaplibreTerradrawControl.ts
src/lib/constants/AvailableModes.ts
src/lib/constants/defaultControlOptions.ts
src/lib/constants/getDefaultModeOptions.ts
src/scss/maplibre-gl-terradraw.scss

fixes #40
the button is only shown in select mode

feat: add  mode to allow users to delete only selected feature.

---

.github/workflows/ci.yml
.gitignore
CONTRIBUTING.md
package.json
playwright.config.ts
pnpm-lock.yaml
tests/routes/demo/index.spec.ts
tests/routes/examples/index.spec.ts
tests/routes/index.spec.ts

added playwright tests for documentation pages

ci: add playwright

---

.changeset/few-meals-cross.md
src/lib/constants/defaultMeasureControlOptions.ts
src/lib/controls/MaplibreMeasureControl.ts

fix: delete unfinished geojson features if measured feature is cancelled. Furtheremore, deleted polygon validation from MeasureControl.

---

.changeset/few-rules-sleep.md
src/lib/constants/getDefaultModeOptions.ts

fixes https://github.com/JamesLMilner/terra-draw/issues/386

fix: fixed bug of polygon validation.

---

.changeset/little-walls-melt.md
.changeset/plenty-turtles-promise.md
package.json
pnpm-lock.yaml
src/lib/constants/AvailableMeasureModes.ts
src/lib/constants/AvailableModes.ts
src/lib/constants/defaultControlOptions.ts
src/lib/constants/defaultMeasureControlOptions.ts
src/lib/constants/getDefaultModeOptions.ts
src/lib/controls/MaplibreTerradrawControl.ts
src/routes/examples/measure-control/+page.svelte
src/scss/maplibre-gl-terradraw.scss

feat: add download button to save features as geojson

---

.changeset/spotty-foxes-tell.md
CONTRIBUTING.md
package.json
src/lib/controls/MaplibreMeasureControl.ts
src/routes/demo/+page.svelte
src/routes/examples/add-geojson/+page.svelte
src/routes/examples/measure-area/+page.svelte
src/routes/examples/measure-distance/+page.svelte
src/routes/examples/select-event/+page.svelte

fix: update properties to include measured distance/area in getFeatures function.

---

.changeset/silly-islands-judge.md
package.json
pnpm-lock.yaml

chore: updated teraddraw to beta.11

---

src/routes/+page.svelte
src/routes/demo/+page.svelte

NPM/CDN code example will be changed according to the selection of control type

doc: allow to swtich between default control and measure control in demo page

---

src/routes/+layout.server.ts
src/routes/api/examples/[slug]/+server.ts
src/routes/examples/[slug]/+page.server.ts
src/routes/helpers.ts

doc: Use CDN specific version for example instead of using latest

---

.github/workflows/release.yml

chore: use full sha tag for ghpage action

---

.changeset/funny-hats-punch.md
src/lib/controls/MaplibreTerradrawControl.ts
src/lib/interfaces/EventTypes.ts

feat: make isExpanded  as a property of MaplibreTerradrawContro to allow users to get or set the state.

---

.changeset/lovely-seals-marry.md
package.json
pnpm-lock.yaml
src/lib/constants/defaultMeasureControlOptions.ts
src/lib/controls/MaplibreMeasureControl.ts
src/lib/controls/MaplibreTerradrawControl.ts
src/lib/interfaces/MeasureControlOptions.ts
src/routes/demo/+page.svelte
static/assets/examples/query-elevation.txt

feat: fetching elevation directly from terrain source

---

.changeset/lovely-bees-divide.md
src/lib/controls/MaplibreMeasureControl.ts
src/routes/demo/+page.svelte

also computeElevation can be changed at demo page.

feat: added computeElevation property in MeasureControl to change setting of the instance.

---

static/assets/examples/add-geojson-customstyle.txt
static/assets/examples/change-style.txt
static/assets/examples/drawing-option.txt

docs: update terradraw CDN version for examples

---

src/app.html
src/routes/+layout.server.ts
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/demo/+page.svelte

docs: improve landing page UI

---

package.json
pnpm-lock.yaml
setupTest.ts
src/lib/controls/MaplibreMeasureControl.test.ts
src/lib/controls/MaplibreTerradrawControl.test.ts
vitest.config.ts

tests: added test for cleanStyle method for each control

---

package.json

docs: exclude references from typedoc

---

.devcontainer/devcontainer.json
.devcontainer/post-create.sh
src/routes/+page.svelte

fix: devcontainer settings

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/post-create.sh

fix: install graphviz to devcontainer for depcruise

---

package.json

chore: upgrade pnpm to v10

---

.changeset/silly-lemons-march.md
src/lib/controls/MaplibreMeasureControl.ts

fix: fixed bug of not removing measure label when draw.removeFeatures to delete features from terra-draw.

---

src/routes/+layout.svelte

fix: fixed footer layout

---

src/routes/+page.svelte
src/routes/CodeBlock.svelte
src/routes/demo/+page.svelte

fix: responsive test

---

pnpm-workspace.yaml
src/routes/CodeBlock.svelte
src/routes/examples/[slug]/+page.svelte

fix: codeblock

---

src/routes/+page.svelte
static/robots.txt

add robots.txt

---

package.json
pnpm-lock.yaml
src/routes/+layout.server.ts
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/CodeBlock.svelte
src/routes/DemoController.svelte
src/routes/DemoMap.svelte

measure control options and selected feature accordion was moved to sidebar

docs: measure control options and selected feature accordion was moved to sidebar

---

src/routes/CodeBlock.svelte
src/routes/DemoController.svelte

docs: fixed CodeBlock to scrollable horizontally

---

src/routes/+page.svelte

docs: add search feature for examples

---

src/routes/CodeBlock.svelte
src/routes/DemoController.svelte
src/routes/DemoMap.svelte

docs: added list box to select a mode to add easily

---

src/routes/DemoMap.svelte

fix: fixed bug of initializing style loading in demo map

---

README.md

docs: add use cases to readme

---

.changeset/great-results-shave.md
dependency-graph.svg
src/lib/controls/MaplibreTerradrawControl.ts
src/lib/interfaces/EventArgs.ts
src/lib/interfaces/index.ts
src/routes/DemoMap.svelte

fix: fixed bug of mode-changed event is not dispatched when mode is changed.

---

src/routes/+page.svelte

Now remember demo settings in URL

docs: remember demo settings as URL params

---

README.md

docs: added geohub to readme as usecase

---

src/routes/+page.svelte
src/routes/DemoMap.svelte
static/assets/maplibre-cdn-example.txt
static/assets/maplibre-npm-example.txt

Now you can see options in code snippet

docs: add measure options to NPM/CDN example from demo settings

---

.github/ISSUE_TEMPLATE/config.yml

docs: added config.yml to link discussion for qa

---

.changeset/better-comics-greet.md
src/lib/controls/MaplibreValhallaControl.ts

fix: fixed bug of getFeatures method of MaplibreValhallaControl to ensure returning all existing features.

---

src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/CodeBlock.svelte
src/routes/DemoMap.svelte
src/routes/examples/[slug]/+page.svelte

- docs: show line number in CodeBlock component
- docs: don't recreate the entire demo map when isExpanded property is changed
- docs: moved footer to +layout.svelte to eliminate duplicated codes

docs: show line number in CodeBlock component

---

.changeset/metal-keys-marry.md
package.json
pnpm-lock.yaml

feat: upgraded terradraw to v1.14.0

---

.changeset/small-actors-travel.md
src/lib/controls/MaplibreMeasureControl.ts

fix: fixed the bug not updating elevation for line feature nodes.

---

src/lib/controls/MaplibreValhallaControl.ts

fix: use updateFeatureGeometry and updateFeatureProeprties in ValhallaControl instead of adding/removing features.

---

tests/routes/index.spec.ts

test: add more e2e tests when other control type
